# Generated by Django 4.0.5 on 2022-06-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact11'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email почта')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
